In [1]:
import requests
import pandas as pd
import json
import os

In [2]:
cwd = os.getcwd()

In [3]:
home_values = pd.read_csv("data/zillow_home_values.csv")

In [6]:
home_values_df = home_values.drop(columns = ["SizeRank", "StateName", "StateCodeFIPS", "MunicipalCodeFIPS"]).fillna(0)
home_values_df.head()

,RegionID,RegionName,RegionType,State,Metro,1996-01-31,1996-02-29,1996-03-31,1996-04-30,1996-05-31,...,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31
0,3101,Los Angeles County,County,CA,Los Angeles-Long Beach-Anaheim,177774.0,177811.0,177880.0,178030.0,178168.0,...,659773.0,664580.0,666444.0,667704.0,672758.0,680207.0,688570.0,695441.0,702046.0,708045.0
1,139,Cook County,County,IL,Chicago-Naperville-Elgin,154331.0,154104.0,153751.0,153625.0,153190.0,...,253684.0,254076.0,254595.0,255333.0,256710.0,258486.0,261016.0,263754.0,266201.0,268475.0
2,1090,Harris County,County,TX,Houston-The Woodlands-Sugar Land,99675.0,99757.0,99768.0,99920.0,100066.0,...,199807.0,200940.0,201912.0,202637.0,203555.0,204670.0,206514.0,208295.0,210494.0,212658.0
3,2402,Maricopa County,County,AZ,Phoenix-Mesa-Scottsdale,116247.0,116575.0,116946.0,117661.0,118356.0,...,299209.0,302766.0,305996.0,309005.0,311980.0,315932.0,320662.0,325809.0,331342.0,337118.0
4,2841,San Diego County,County,CA,San Diego-Carlsbad,180788.0,180437.0,180244.0,179839.0,179653.0,...,615413.0,618539.0,622620.0,625616.0,629734.0,636244.0,645855.0,656702.0,667613.0,678665.0

In [8]:
region_name = home_values_df["RegionName"]

In [ ]:
for